#!/usr/bin/env python3
import sys
import time


def is_prime(n):
    """Checks if a number is prime"""
    if n < 2:
        return False
    else:
        for i in range(2, int(n**0.5) + 1):
            if n % i == 0:
                return False
        return True


def factorize(n):
    """Factorizes a number into its prime factors"""
    p = None
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            p = i
            break
    q = n // p
    return p, q


if __name__ == "__main__":
    with open(sys.argv[1], 'r') as file:
        n = int(file.read().strip())
    p, q = factorize(n)
    if p is not None and q is not None:
        print(f"{n}={p}*{q}")
